name: Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: $
      - run: yarn install
        working-directory: ./typescript-version
      - run: yarn build --base=/materio-vuetify-vuejs-admin-template-free/demo/
        working-directory: ./typescript-version
      - name: Upload dist content via scp
        uses: appleboy/scp-action@master
        env:
          HOST: $
          USERNAME: $
          PORT: $
          KEY: $
        with:
          source: ./typescript-version/dist
          target: $
#       - name: Replace old demo
#         uses: appleboy/ssh-action@master
#         with:
#           host: $
#           USERNAME: $
#           PORT: $
#           KEY: $
#           script: mkdir -p $ && if [ -d $/demo ]; then mv $/demo $/demo-old; fi && mv $/dist $/demo && rm -rf $/demo-old
